//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewModelEx_S1.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eng_ModelAction
    {
        public int id_modelact { get; set; }
        public int id_depmodel { get; set; }
        public int id_jobitem { get; set; }
        public string status_job { get; set; }
        public string name_responsible { get; set; }
        public string emailsend { get; set; }
        public string plandate { get; set; }
        public string comment_admin { get; set; }
        public string comment_admin_reject { get; set; }
        public string dateadd_amin { get; set; }
        public string empid { get; set; }
        public string name_docpdf { get; set; }
        public string name_docexcel { get; set; }
        public string name_image { get; set; }
        public string comment_user { get; set; }
        public string date_userupdate { get; set; }
        public string date_useradd { get; set; }
    }
}
