//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewModelEx_S1.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eng_JobItemList
    {
        public int job_itemid { get; set; }
        public string job_itemname { get; set; }
    }
}
