//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewModelEx_S1.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eng_AddDepartmentModel
    {
        public int adddpmodel_id { get; set; }
        public string model_subnew { get; set; }
        public int dept_id { get; set; }
        public string status_appord { get; set; }
        public string date_add { get; set; }
        public string model_masterdrawingid { get; set; }
    }
}
