//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewModelEx_S1.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eng_ModelSub
    {
        public int model_subid { get; set; }
        public string model_drawingid { get; set; }
        public string drawing { get; set; }
        public string modelname { get; set; }
        public string partname { get; set; }
        public string revision { get; set; }
        public string other_commment { get; set; }
        public string date_add { get; set; }
        public string date_update { get; set; }
    }
}
