//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewModelEx_S1.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eng_newModel
    {
        public string model_drawingid { get; set; }
        public string model_name { get; set; }
        public string mode_partname { get; set; }
        public string id_customer { get; set; }
        public string model_datedoc { get; set; }
        public string model_date { get; set; }
        public string otherdetail { get; set; }
        public string status_modelid { get; set; }
        public string customer_partname { get; set; }
        public string version { get; set; }
    }
}
